In [9]:
a, b = 0,1

In [10]:
while a < 10:
    print(a)
    a,b = b,a+b

0
1
1
2
3
5
8


In [14]:
a,b = 0,1
while a < 1000:
    print(a, end = ',')
    a,b = b, a+b

0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,

In [16]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
import numpy as np
np.array(L)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.array([3.14,2,0])

array([3.14, 2.  , 0.  ])

In [22]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [26]:
for i in range(5):
    print(i)

0
1
2
3
4


In [28]:
a,b = 0,1
while a < 1000:
    print(a, end = ',')
    a,b = b, a+b

0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,

In [30]:
x = int(input("Please input an interger: "))

Please input an interger: 66


In [34]:
if x < 0:
    x = 0 
    print('Negative changed to zero')
elif x == 0:
    print('Zero')
elif x == 1:
    print('One')
else:
    print('More')

More


In [36]:
words = ['cat', 'window', 'defenestrate']

In [38]:
for w in words:
    print(w, len(w))

cat 3
window 6
defenestrate 12


In [43]:
for n in range(2,11):
    for x in range(2,n):
        if n % x == 0:
            print(n, 'equals',x,'*',n//x)
            break
    else:
        print(n,'is a prime number')

2 is a prime number
3 is a prime number
4 equals 2 * 2
5 is a prime number
6 equals 2 * 3
7 is a prime number
8 equals 2 * 4
9 equals 3 * 3
10 equals 2 * 5


In [45]:
for num in range(1,10):
    if num%2 == 0:
        print(num,'is an even num')
        continue
    print('Found a num:',num)

Found a num: 1
2 is an even num
Found a num: 3
4 is an even num
Found a num: 5
6 is an even num
Found a num: 7
8 is an even num
Found a num: 9


In [1]:
L= list()

In [4]:
def fib(n):
    a,b = 0,1
    i = 0
    while a < n:
        print(a, end = ' ')
        a,b = b,a+b
    L.append(a)

In [5]:
fib(100)

0 1 1 2 3 5 8 13 21 34 55 89 

In [6]:
L

[144]

In [11]:
var = '01234567'

In [12]:
print(var[::2])

0246


In [13]:
A=(0,1,2,3)

In [14]:
A[end]

NameError: name 'end' is not defined

In [15]:
A[3]

3

In [16]:
B=["a","b","c"]

In [17]:
B[1:]

['b', 'c']

In [18]:
S={'A','B','C'}

U={'A','Z','C'}

U.union(S)

{'A', 'B', 'C', 'Z'}

In [21]:
age = 12
if age > 18:
    print('You can enter')
print('Move on')

Move on


In [29]:
age = int(input())

if age < 18:
    print('Go see another show')
else:
    print('You can enter')
print('Move on')

22
You can enter
Move on


In [31]:
age = int(input())

if age > 18:
    print("U can enter")
elif age == 18:
    print("use back gate")
else:
    print("please exit")
print("Move on")

18
use back gate
Move on


In [38]:
colour = ['red', 'blue','black']
l = len(colour)

In [39]:
for i in range(l):
    colour[i] = 'white'
    
colour

['white', 'white', 'white']

In [44]:
for i in colour:
    print(i, end = " ")

white white white 

In [45]:
A=['1','2','3']

for a in A:

print(2*a)

IndentationError: expected an indented block (<ipython-input-45-77536e7097e4>, line 5)

In [1]:
int(3.2)

3

In [2]:
Name="Michael Jackson"

In [3]:
Name.find('el')

5

In [4]:
A=((11,12),[21,22])

In [6]:
A[1]

[21, 22]

In [7]:
'1,2,3,4'.split(',')

['1', '2', '3', '4']

This is from the udemy cource 

In [1]:
mystring = "Hello World"

In [2]:
mystring[0]

'H'

In [2]:
string = 'asdfghjkl'

In [3]:
string[2:]

'dfghjkl'

In [4]:
string[:-1]

'asdfghjk'